### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gguuss**
Adds example commands for various processes to fix [this issue](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/issues/187)

### CODE REVIEW

**Comment by amarkevich** [comment]
@gguuss Could you prepare a release?

**Comment by gguuss** [comment]
Feels like a good time for it, I'll verify and can do this.

**Comment by gguuss** [comment]
Looks like ESP8266 is crashing, I tried multiple boards.  My computer is acting up, might have to try again in the morning.

**Comment by amarkevich** [comment]
My env:
Arduino IDE 1.8.13
Arduino core for ESP8266 2.7.4
arduino-mqtt 2.4.7
google-cloud-iot-arduino from master

Board: NodeMCU 1.0 (ESP-12E Module), 3 pcs

**Comment by gguuss** [comment]
I'll try again now, but I have verified the MKR-1000 and ESP32 so it's probably on my end.  FWIW I'm on Arduino 1.8.10, ESP Core 2.7.4, and MQTT 2.4.7. The crash is occurring in the library where the board is connecting to the MQTT commands topic.

**Comment by gguuss** [comment]
My stack trace, I'm going to look further into this:

```
Exception 28: LoadProhibited: A load referenced a page mapped with an attribute that does not permit loads
PC: 0x402104f2: pgm_read_byte_inlined at /home/earle/src/esp-quick-toolchain/repo/newlib/newlib/libc/sys/xtensa/sys/pgmspace.h line 72
EXCVADDR: 0x00000000

Decoding stack results
0x40212a04: __ssputs_r at /home/earle/src/esp-quick-toolchain/repo/newlib/newlib/libc/stdio/nano-vfprintf.c line 180
0x4020ec09: _printf_i at /home/earle/src/esp-quick-toolchain/repo/newlib/newlib/libc/stdio/nano-vfprintf_i.c line 226
0x40212ace: __ssputs_r at /home/earle/src/esp-quick-toolchain/repo/newlib/newlib/libc/stdio/nano-vfprintf.c line 233
0x40221c4f: ip_chksum_pseudo at core/inet_chksum.c line 395
0x40212eff: _svfprintf_r at /home/earle/src/esp-quick-toolchain/repo/newlib/newlib/libc/stdio/nano-vfprintf.c line 667
0x4010093b: free(void*) at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/umm_malloc/umm_malloc.cpp line 398
0x40212fd1: operator delete(void*) at /workdir/repo/gcc/libstdc++-v3/libsupc++/del_op.cc line 48
0x4020a686: __delay(unsigned long) at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/core_esp8266_wiring.cpp line 54
0x402104a1: _vsnprintf_r at /home/earle/src/esp-quick-toolchain/repo/newlib/newlib/libc/stdio/vsnprintf.c line 73
0x40206f25: WiFiClient::flush(unsigned int) at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/libraries/ESP8266WiFi/src/WiFiClient.cpp line 318
0x40207f12: BearSSL::WiFiClientSecure::flush(unsigned int) at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp line 212
0x40207f2c: BearSSL::WiFiClientSecure::flush() at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h line 63
0x40207fd6: BearSSL::WiFiClientSecure::_write(unsigned char const*, unsigned int, bool) at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp line 297
0x402104e4: vsnprintf at /home/earle/src/esp-quick-toolchain/repo/newlib/newlib/libc/stdio/vsnprintf.c line 42
0x40208004: BearSSL::WiFiClientSecure::write(unsigned char const*, unsigned int) at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp line 309
0x402086a6: lwmqtt_arduino_timer_set(void*, unsigned int) at /Users/class/Documents/Arduino/libraries/MQTT/src/MQTTClient.cpp line 13
0x40209304: Print::printf(char const*, ...) at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/Print.cpp line 63
0x4010026a: millis() at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/core_esp8266_wiring.cpp line 188
0x4020a0a8: optimistic_yield(uint32_t) at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/core_esp8266_main.cpp line 151
0x4020c409: MQTTClient::connected() at /Users/class/Documents/Arduino/libraries/MQTT/src/MQTTClient.cpp line 393
0x40202178: messageReceivedAdvanced(MQTTClient*, char*, char*, int) at /var/folders/w8/y0hz57jn5pb65ptmyfs_dy1w0055ky/T/arduino_build_685179/sketch/esp8266_mqtt.h line 38
0x40208620: MQTTClientHandler(lwmqtt_client_t*, void*, lwmqtt_string_t, lwmqtt_message_t) at /Users/class/Documents/Arduino/libraries/MQTT/src/MQTTClient.cpp line 100
0x40208728: lwmqtt_arduino_network_read(void*, unsigned char*, unsigned int, unsigned int*, unsigned int) at /Users/class/Documents/Arduino/libraries/MQTT/src/MQTTClient.cpp line 44
0x40201b7f: lwmqtt_decode_publish at /Users/class/Documents/Arduino/libraries/MQTT/src/lwmqtt/packet.c line 448
0x402098b1: String::invalidate() at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/WString.cpp line 140
0x4020110e: lwmqtt_cycle_until at /Users/class/Documents/Arduino/libraries/MQTT/src/lwmqtt/client.c line 219
0x4010026a: millis() at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/core_esp8266_wiring.cpp line 188
0x402098d0: String::~String() at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/WString.cpp line 125
0x40201216: lwmqtt_yield at /Users/class/Documents/Arduino/libraries/MQTT/src/lwmqtt/client.c line 353
0x4020c409: MQTTClient::connected() at /Users/class/Documents/Arduino/libraries/MQTT/src/MQTTClient.cpp line 393
0x40208aac: MQTTClient::loop() at /Users/class/Documents/Arduino/libraries/MQTT/src/MQTTClient.cpp line 369
0x4020276b: CloudIoTCoreMqtt::loop() at /Users/class/Documents/Arduino/libraries/google-cloud-iot-arduino/src/CloudIoTCoreMqtt.cpp line 40
0x402023ed: loop() at /var/folders/w8/y0hz57jn5pb65ptmyfs_dy1w0055ky/T/arduino_modified_sketch_92743/Esp8266-lwmqtt.ino line 57
0x4010019d: esp_schedule() at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/core_esp8266_main.cpp line 125
0x4020a150: loop_wrapper() at /Users/class/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/cores/esp8266/core_esp8266_main.cpp line 197
```

**Comment by gguuss** [comment]
I have been trying this now for 2 hours changing various aspects and I'm suspecting that a bug was introduced affecting ESP8266 since the last release.

**Comment by amarkevich** [comment]
> 0x40201216: lwmqtt_yield at /Users/class/Documents/Arduino/libraries/MQTT/src/lwmqtt/client.c line 353
there is no any String object in this function...

**Comment by amarkevich** [comment]
@gguuss check #202 , fix for fresh device with empty config

**Pull request merged**
