### PR TITLE
Updates portable random number generator

### PR DESCRIPTION
**Pull request by gguuss**

### CODE REVIEW

**Comment by gguuss** [comment]
@alvarowolfx /FYI, prng is hardcoding the random values it is generating and we should replace it with optimal / portable random.

**Comment by alvarowolfx** [comment]
Maybe we can use the built-in Arduino `Math.random` because on each board it seems to use the internal true random generator. At least on ESP32 and ESP8266 I found some evidences that they use the right function.

ESP8266 : https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/cores/esp8266/WMath.cpp#L40

ESP32: https://github.com/espressif/arduino-esp32/blob/49f35ff070fcb8c82a11866ae6f81bab49dba6e3/cores/esp32/WMath.cpp#L38

**Comment by alvarowolfx** [comment]
For the MKR1000 Board, I didn't found yet enough information, but it seems that the Arduino SAMD Core uses the `rand()` functions but I cannot find if this is the correct way. 

https://github.com/arduino/ArduinoCore-samd/blob/2facbf6177ef568b9f05cce204c1563bfa6362e4/cores/arduino/WMath.cpp#L40

**Comment by gguuss** [comment]
@alvarowolfx - I'll see about using **Math.random**, also updated README in this PR as we've been accepted into the Arduino Library Manager!

**Comment by alvarowolfx** [comment]
Cool @gguuss, good to know that soon we will show up on Arduino Library Manager. :tada: :tada:

**Comment by gguuss** [comment]
@alvarowolfx FYI, I'm going with Arduino's random(long, long) function -- this requires us to switch the library files to be C++ instead of C.

**Pull request merged**
